apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ybes437lr-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ybes437lr-go 
  name: ybes437lr-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ybes437lr-go 
